IF (GVT_MPI)
        FIND_PACKAGE(MPI REQUIRED)
        INCLUDE_DIRECTORIES(${MPI_INCLUDE_PATH})

	MACRO(CONFIGURE_LIB_MPI)
            set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "${MPI_COMPILE_FLAGS} -DPARALLEL")
            set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "${MPI_LINK_FLAGS}")
	ENDMACRO()




ENDIF()
